# Generated by Django 5.0.1 on 2024-01-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="provider_url",
            new_name="provider_id",
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("EN", "English"), ("FR", "French"), ("KR", "Korean")],
                default="KR",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twoFactor",
            field=models.BooleanField(default=True),
        ),
    ]
