# Generated by Django 5.0.1 on 2024-02-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_emailverification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="type",
            field=models.CharField(
                choices=[("LOGIN", "login"), ("PASS", "pass")],
                default="LOGIN",
                max_length=5,
            ),
        ),
    ]
