# Generated by Django 5.0.2 on 2024-02-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_user_login_alter_emailverification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
