# Generated by Django 5.0.1 on 2024-02-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_user_intraid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="intraId",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
