# Generated by Django 5.0.1 on 2024-02-15 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_user_intraid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="intraId",
        ),
    ]
