# Generated by Django 5.0.1 on 2024-02-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_remove_user_intraid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="intraId",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
