# Generated by Django 5.0.1 on 2024-02-22 04:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_remove_user_intraid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="twoFactor",
            new_name="is_2fa",
        ),
    ]
