# Generated by Django 5.0.1 on 2024-02-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_emailverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="type",
            field=models.CharField(
                choices=[("LOGIN", "login"), ("PASS", "pass")],
                default="LOGIN",
                max_length=5,
            ),
        ),
        migrations.AlterModelTable(
            name="emailverification",
            table="user_email_verification",
        ),
    ]
