# Generated by Django 5.0.1 on 2024-03-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_emailverification_type_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='type',
            field=models.CharField(choices=[('PASS', 'pass'), ('LOGIN', 'login')], default='LOGIN', max_length=5),
        ),
    ]
