# Generated by Django 5.0.1 on 2024-02-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_emailverification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
