# Generated by Django 5.0.1 on 2024-02-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_emailverification_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="type",
            field=models.CharField(
                choices=[("PASS", "pass"), ("LOGIN", "login")],
                default="LOGIN",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=1000, verbose_name="password"),
        ),
    ]
