version: '3.1'

services:

  db:
    container_name: postgres
    env_file:
      - .env
    ports:
     - "15432:5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  adminer:
    image: adminer
    restart: always
    ports:
      - "5555:8080"