version: '3.1'

services:

  db:
    container_name: postgres
    ports:
     - "15432:5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ts
  adminer:
    image: adminer
    restart: always
    ports:
      - "5555:8080"