# Generated by Django 5.0.1 on 2024-01-22 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="player2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player2_games",
                to="user.appuser",
            ),
        ),
    ]
