# Generated by Django 5.0.1 on 2024-01-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
