# Generated by Django 5.0.1 on 2024-01-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_alter_appuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='image',
            field=models.BinaryField(null=True),
        ),
    ]
