# Generated by Django 5.0.1 on 2024-01-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0003_alter_appuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
