# Generated by Django 5.0.1 on 2024-01-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('KO', 'Korean'), ('ES', 'Spanish')], default='EN', max_length=2),
        ),
        migrations.AlterField(
            model_name='friends',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20),
        ),
    ]
