# Generated by Django 5.0.1 on 2024-01-10 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_appuser_language_alter_friends_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='provider',
            field=models.CharField(default='google', max_length=50),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='provider_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
